name: 'laplap_analytics'
version: '1.0.0'
config-version: 2

profile: 'laplap_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshot"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  laplap_analytics:
    staging:
      +materialized: view